version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      npm-dev:
        applies-to: version-updates
        dependency-type: development
      npm-prod:
        applies-to: version-updates
        dependency-type: production
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        applies-to: version-updates
        dependency-type: production
